<?php

	define("TITLE_OF_PROJECT", "CLAUDIO SMART HOME");
	define("INTERNET_CONNECTED_MODE", true);	// Se deve provare connessioni esterne, altrimenti non attende il timeout...

	define("URL_TO_STATUS_FILE", "http://192.168.1.201/status.xml"); // URL to the status xml file generated by relays board
//	define("URL_TO_STATUS_FILE", "../status_example.xml"); // URL to the status xml file generated by relays board
	define("URL_TO_REMOTE_CONTROL_XML_FILE", "./remoteControl.xml"); // URL to the remote control status xml with avtual status
	define("ASSOCIATED_NAMES_XML_FILES", "./nomi_associati.xml"); // Il file che specifica i nomi assegnati ai vari relays

	define("LOCAL_PATH_TO_IP_CAM", "http://192.168.1.202"); // url to embed for webcam
	define("PORT_TO_IP_CAM", "8080"); // port to add to public IP to show webcam
	define("LOCAL_PATH_TO_IP_CAM_2", "http://192.168.1.204"); // url to embed for webcam
	define("PORT_TO_IP_CAM_2", "8081"); // port to add to public IP to show webcam
	define("ROOT_PATH_FOR_BOARD_COMMAND", "http://192.168.1.201/forms.htm?"); // ex: http://192.168.1.201/forms.htm?led0=1
	define("REFRESH_PERIOD_FOR_AJAX_CALL", "20000"); // Express in milliseconds
	define("REFRESH_PERIOD_FOR_AJAX_CALL_INVERTER", "20000"); // Express in milliseconds
	define("REFRESH_PERIOD_FOR_AJAX_CALL_ENEL", "20000"); // Express in milliseconds
	define("TIME_TO_PRESS_RELAYS", "2"); // Express in seconds, the sleep of PHP before ajax responding

	define("LIST_OF_XML_RELAYS_NAMES", "led0:led1:led2:led3:led4:led5:led6:led7"); // list of Relays names by relays board
	define("LIST_OF_XML_TEMP_INPUT_NAMES", "tem1:tem2:tem3:tem4"); // list of temp Input names by relays board
	define("LIST_OF_XML_POT_INPUT_NAMES", "pot0:pot1:pot2:pot3"); // list of elect Input names by relays board
	define("LIST_OF_XML_UMID_INPUT_NAMES", "umi1:umi2:umi3:umi4"); // list of umi Input names by relays board

	define("ACCESO_LABEL", "ACCESO"); // acceso
	define("SPENTO_LABEL", "SPENTO"); // spento

	define("HOURS_TO_EXCLUDE_IN_INVERTER_STATISTICS", "22:23:24:00:01:02:03:04"); // list of Relays names by relays board

	// crepuscolare
	define("FORCE_NIGHT_SWITCH_OFF", 2); // if -1 will turn off at dawn
	define("CREPUSCOLAR_LATITUDE", 41.46); // cooridnates of the place
	define("CREPUSCOLAR_LONGITUDE", 12.90); // cooridnates of the place
	
	
	// Define temperature Range
	define("VERY_COLD_VALUE", 15); // bLu
	define("COLD_VALUE", 19); // azzurro
	define("HOT_VALUE", 26); // giallo
	define("VERY_HOT_VALUE", 30); // arancio
	
	// Define umidita Range
	define("VERY_BASSA_VALUE", 25); // bLu
	define("BASSA_VALUE", 39); // azzurro
	define("ALTA_VALUE", 66); // giallo
	define("VERY_ALTA_VALUE", 80); // arancio

	// Define interface access account
	define("SMART_USERNAME", "admin"); 
	define("SMART_PASSWORD", "c"); 

	// Define DB access account 
	define("DB_HOST", "localhost"); 
	define("DB_NAME", "claudio"); 
	define("DB_USER", "phpmyadmin"); 
	define("DB_PASSWORD", "Claudio816431"); 

	// Define e-mail account for SENDER
	define("EMAIL_SENDER_ADDRESS", "smarthomenotify@gmail.com"); 
	define("EMAIL_SENDER_USER", "smarthomenotify@gmail.com"); 
	define("EMAIL_SENDER_PASSWORD", "smarthome"); 
	define("EMAIL_SENDER_NAME", "Smart Home Lucio"); 

	// Define e-mail account TO NOTIFY
	define("EMAIL_NOTIFICATION_ADDRESS", "luciomonter@gmail.com"); 
	define("EMAIL_NOTIFICATION_NAME", "Lucio Notification"); 
	define("EMAIL_NOTIFICATION_ADDRESS_SECOND", "c.monterubbiano@gmail.com"); // Se presente secondo indirizzo di notifica, puo' essere  vuoto:
	//define("EMAIL_NOTIFICATION_ADDRESS_SECOND", ""); // Esempio vuoto
	define("EMAIL_NOTIFICATION_NAME_SECOND", "Claudio Notification"); // Se presente secondo nome di notifica

	// PUBLIC IP ADDRESS
	define("URL_TO_GET_PUBLIC_IP_CALLBACK", "http://www.luciomonter.com/callbackip.php"); 
	define("DIRECTORY_ON_LOCAL_WEBSERVER", "smartHome/"); 
	define("WEBSERVER_FORWARDED_PORT", "80"); 
	
	
	// Pinza amperometrica
	define("TOLLERANZA_PINZA_AMPEROMETRICA", "150"); 
	
	
	// Claudio
	define("MAX_TIME_AGG", 30);	// Massimo tempo tra un aggiornamento e l'altro
								// prima di considerare interrotto espresso in secondi
	define("TIME_AGG_STA", 3600);	// Massimo tempo in secondi tra un aggiornamento e l'altro

?>
