#!/usr/bin/env python3

import argparse
import signal
import sys
import time
import logging

#   Aggiunta da  me
#import commands
import subprocess
#   Fine aggiunta da  me
out_file = open("leggi_433.txt","a")
out_file.write("Fase 1\nLook at it and see\n")
out_file.close()
from rpi_rf import RFDevice

rfdevice = None

# pylint: disable=unused-argument
def exithandler(signal, frame):
    rfdevice.cleanup()
    sys.exit(0)

logging.basicConfig(level=logging.INFO, datefmt='%d/%m/%Y %H:%M:%S',
                    format='%(asctime)-15s - [%(levelname)s] %(module)s: %(message)s', )
subprocess.call(['php', '/var/www/html/Claudio/readwriteDb.php', ("Lancio_Lettura_433")])
out_file = open("leggi_433.txt","a")
out_file.write("Fase 2\nLook at it and see\n")
out_file.close()
parser = argparse.ArgumentParser(description='Receives a decimal code via a 433/315MHz GPIO device')
parser.add_argument('-g', dest='gpio', type=int, default=27,
                    help="GPIO pin (Default: 27)")
args = parser.parse_args()

signal.signal(signal.SIGINT, exithandler)
rfdevice = RFDevice(args.gpio)
rfdevice.enable_rx()
timestamp = None
tempo =0
logging.info("Listening for codes on GPIO " + str(args.gpio))
while True:
    if rfdevice.rx_code_timestamp != timestamp and rfdevice.rx_code > 99999 and rfdevice.rx_code < 10000000 and rfdevice.rx_proto ==1:
        subprocess.call(['php', '/var/www/html/Claudio/readwriteDb.php', ("lettura_433|" + str(rfdevice.rx_code) +"|" + str(rfdevice.rx_pulselength) + "|" + str(rfdevice.rx_proto))])
        timestamp = rfdevice.rx_code_timestamp
    elif rfdevice.rx_code_timestamp != timestamp:
        timestamp = rfdevice.rx_code_timestamp
        logging.info(str(rfdevice.rx_code) +
                     " [pulselength " + str(rfdevice.rx_pulselength) +
                     ", protocol " + str(rfdevice.rx_proto) + "]")
    time.sleep(0.01)
rfdevice.cleanup()
